/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.Administrador;
import controladores.Socio;
import controladores.SoporteTécnico;

/**
 *
 * @author francobmassi
 */
public class AdminstrarAltaDeClientes extends javax.swing.JFrame {
    
    private SoporteTécnico soporteTécnico;
    private Administrador admin;
    private String altaUsuario;
    
    public void setST(SoporteTécnico soporteTécnico){
        this.soporteTécnico = soporteTécnico;
    }
    
    public void setAdmin(Administrador admin){
        this.admin = admin;
    }
    
    public String strHTML(String texto) {
        return "<html>" + texto + "</html>";
    }
    
    /**
     * Creates new form AdminstrarAltaDeClientes
     */
    public AdminstrarAltaDeClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAsignasionDeSedes = new javax.swing.JPanel();
        clienteUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mostrarClientes = new javax.swing.JButton();
        asignarSede = new javax.swing.JButton();
        alta = new javax.swing.JButton();
        baja = new javax.swing.JButton();
        resultadosDeBusqueda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienteUsername.setText("Ingrese el username cliente...");
        clienteUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteUsernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("ADMINSTRAR ALTA DE CLIENTES");

        mostrarClientes.setText("MOSTRAR CLIENTES");
        mostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarClientesActionPerformed(evt);
            }
        });

        asignarSede.setText("ASIGNAR SEDE");
        asignarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarSedeActionPerformed(evt);
            }
        });

        alta.setText("ASIGNAR SEDE");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });

        baja.setText("ASIGNAR SEDE");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });

        resultadosDeBusqueda.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N

        javax.swing.GroupLayout PanelAsignasionDeSedesLayout = new javax.swing.GroupLayout(PanelAsignasionDeSedes);
        PanelAsignasionDeSedes.setLayout(PanelAsignasionDeSedesLayout);
        PanelAsignasionDeSedesLayout.setHorizontalGroup(
            PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addGroup(PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAsignasionDeSedesLayout.createSequentialGroup()
                        .addComponent(asignarSede)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAsignasionDeSedesLayout.createSequentialGroup()
                        .addComponent(mostrarClientes)
                        .addGap(271, 271, 271))))
            .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addGroup(PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(alta, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clienteUsername))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        PanelAsignasionDeSedesLayout.setVerticalGroup(
            PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baja, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(asignarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAsignasionDeSedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAsignasionDeSedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteUsernameActionPerformed

    private void mostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarClientesActionPerformed
        String devolver = "";
        for (Socio socio: soporteTécnico.getClientes()) {
            devolver += "<p>CLIENTE : " + socio.getUsername() +".</p>";
        }
        resultadosDeBusqueda.setText(strHTML(devolver));
    }//GEN-LAST:event_mostrarClientesActionPerformed

    private void asignarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarSedeActionPerformed
        String username = clienteUsername.getText().toUpperCase();
        boolean existe_socio = false;
        for (Socio socio: soporteTécnico.getClientes()) {
            if (socio.getUsername().equals(username)){
                admin.gestionarAltaCliente(username, altaUsuario);
                existe_socio = true;
            }
        }
        if (!existe_socio) {
            IngresoErroneo ingresoErroneo = new IngresoErroneo();
            ingresoErroneo.setVisible(true);
            ingresoErroneo.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_asignarSedeActionPerformed

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        this.altaUsuario = "ALTA";
    }//GEN-LAST:event_altaActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        this.altaUsuario = "BAJA";
    }//GEN-LAST:event_bajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAsignasionDeSedes;
    private javax.swing.JButton alta;
    private javax.swing.JButton asignarSede;
    private javax.swing.JButton baja;
    private javax.swing.JTextField clienteUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostrarClientes;
    private javax.swing.JLabel resultadosDeBusqueda;
    // End of variables declaration//GEN-END:variables
}
