/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.Administrador;
import controladores.SoporteTécnico;
import sistema.Sede;

/**
 *
 * @author francobmassi
 */
public class AsignarSedes extends javax.swing.JFrame {
    
    private SoporteTécnico soporteTécnico;
    
    public void setST(SoporteTécnico soporteTécnico){
        this.soporteTécnico = soporteTécnico;
    }
    
    /**
     * Creates new form AsignarSedes
     */
    public AsignarSedes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAsignasionDeSedes = new javax.swing.JPanel();
        adminUsername = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        asignarSede = new javax.swing.JButton();
        botonVolverAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminUsername.setText("Ingrese el username del adminstrador...");
        adminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameActionPerformed(evt);
            }
        });

        location.setText("Ingrese la ubiciación de la sede...");
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("ASIGNAR SEDES A ADMINISTRADORES");

        asignarSede.setText("ASIGNAR SEDE");
        asignarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarSedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAsignasionDeSedesLayout = new javax.swing.GroupLayout(PanelAsignasionDeSedes);
        PanelAsignasionDeSedes.setLayout(PanelAsignasionDeSedesLayout);
        PanelAsignasionDeSedesLayout.setHorizontalGroup(
            PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminUsername)
                    .addComponent(location))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(asignarSede)
                .addGap(298, 298, 298))
            .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PanelAsignasionDeSedesLayout.setVerticalGroup(
            PanelAsignasionDeSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsignasionDeSedesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        botonVolverAtras.setText("VOLVER ATRÁS");
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAsignasionDeSedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(botonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAsignasionDeSedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void asignarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarSedeActionPerformed
        String admin = adminUsername.getText();
        String nombreSede = location.getText();
        boolean existe_username = false;
        boolean existe_sede = false; 
        for (Administrador administrador: soporteTécnico.getAdministradores()) {
    		if (administrador.getUsername().equals(admin.toUpperCase())) {
                    existe_username = true;
                }
        }
        for (Sede sede: soporteTécnico.getSedes()) {
                if (sede.getUbicacion().equals(nombreSede.toUpperCase())) {
                        existe_sede = true;
                }
            }
        if (existe_username && existe_sede) {
            soporteTécnico.asignarSede(nombreSede, admin);
        } else {
            IngresoErroneo ingresoErroneo = new IngresoErroneo();
            ingresoErroneo.setVisible(true);
            ingresoErroneo.setLocationRelativeTo(null);
        }
        adminUsername.setText("");
        location.setText("");

    }//GEN-LAST:event_asignarSedeActionPerformed

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdministracionDeClientes;
    private javax.swing.JPanel PanelAdministracionDeClientes1;
    private javax.swing.JPanel PanelAsignasionDeSedes;
    private javax.swing.JTextField adminUsername;
    private javax.swing.JButton asignarSede;
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField newUserName;
    private javax.swing.JTextField newUserName1;
    // End of variables declaration//GEN-END:variables
}
