/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import articulos.*;
import controladores.SoporteTécnico;

/**
 *
 * @author francobmassi
 */
public class CreacionDeArticulos extends javax.swing.JFrame {
    
    private SoporteTécnico soporteTécnico;
    
    public void setST(SoporteTécnico soporteTécnico){
        this.soporteTécnico = soporteTécnico;
    }
    
    /**
     * Creates new form CrearArticulos
     */
    public CreacionDeArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearArticulos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonVolverAtras = new javax.swing.JButton();
        crearNuevaPesa = new javax.swing.JButton();
        crearNuevaColchoneta = new javax.swing.JButton();
        crearNuevoArtPers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resultadosDeBusqueda = new javax.swing.JLabel();
        mostrarArticulos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("ARTICULOS EXISTENTES");

        botonVolverAtras.setText("VOLVER ATRÁS");
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });

        crearNuevaPesa.setText("PESA");
        crearNuevaPesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevaPesaActionPerformed(evt);
            }
        });

        crearNuevaColchoneta.setText("COLCHONETA");
        crearNuevaColchoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevaColchonetaActionPerformed(evt);
            }
        });

        crearNuevoArtPers.setText("ARTICULO PERSONALIZADO");
        crearNuevoArtPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevoArtPersActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setText("CREAR NUEVO ARTICULO");

        mostrarArticulos.setText("MOSTRAR ARTICULOS EXISTENTES");
        mostrarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarArticulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearArticulosLayout = new javax.swing.GroupLayout(crearArticulos);
        crearArticulos.setLayout(crearArticulosLayout);
        crearArticulosLayout.setHorizontalGroup(
            crearArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearArticulosLayout.createSequentialGroup()
                .addGroup(crearArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearArticulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crearArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearNuevaColchoneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearNuevoArtPers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearNuevaPesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                            .addComponent(botonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(crearArticulosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(crearArticulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mostrarArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        crearArticulosLayout.setVerticalGroup(
            crearArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearNuevaPesa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearNuevaColchoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearNuevoArtPers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(botonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(crearArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(crearArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearNuevaPesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevaPesaActionPerformed
        CreacionNuevaPesa nuevaPesa = new CreacionNuevaPesa();
        nuevaPesa.setST(soporteTécnico);
        nuevaPesa.setVisible(true);
        nuevaPesa.setLocationRelativeTo(null);
    }//GEN-LAST:event_crearNuevaPesaActionPerformed

    private void crearNuevaColchonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevaColchonetaActionPerformed
        CreacionNuevaColchoneta nuevaColchoneta = new CreacionNuevaColchoneta();
        nuevaColchoneta.setST(soporteTécnico);
        nuevaColchoneta.setVisible(true);
        nuevaColchoneta.setLocationRelativeTo(null);
    }//GEN-LAST:event_crearNuevaColchonetaActionPerformed

    private void crearNuevoArtPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevoArtPersActionPerformed
        CreacionNuevoArtPers nuevoArtPers =new CreacionNuevoArtPers();
        nuevoArtPers.setST(soporteTécnico);
        nuevoArtPers.setVisible(true);
        nuevoArtPers.setLocationRelativeTo(null);
    }//GEN-LAST:event_crearNuevoArtPersActionPerformed

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverAtrasActionPerformed

    private void mostrarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarArticulosActionPerformed
        String devolver = "";
        for (Articulo art: soporteTécnico.getArticulos()) {
            if (art instanceof Pesa || art instanceof Colchoneta) {
                devolver += "<p>ARTICULO: " + art.getTipo() + " - " + art.getMarca() + " - " + art.getTipoAmortizacion() + " - " + art.getDuracion() + ".</p>";
            } else {
                ArticuloPersonalizado artp = (ArticuloPersonalizado) art;
                devolver += "<p>ARTICULO: " + artp.getTipo() + " - " + artp.getMarca() + " - " + artp.getDescripcion() + " - " + artp.getTipoAmortizacion() + " - " + artp.getDuracion() + ".</p>";
            }
        }
        resultadosDeBusqueda.setText(strHTML(devolver));
    }//GEN-LAST:event_mostrarArticulosActionPerformed

    public String strHTML(String texto) {
        return "<html>" + texto + "</html>";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JPanel crearArticulos;
    private javax.swing.JButton crearNuevaColchoneta;
    private javax.swing.JButton crearNuevaPesa;
    private javax.swing.JButton crearNuevoArtPers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mostrarArticulos;
    private javax.swing.JButton mostrarClientes;
    private javax.swing.JButton mostrarClientes1;
    private javax.swing.JLabel resultadosDeBusqueda;
    // End of variables declaration//GEN-END:variables
}
