/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.SoporteTécnico;
import sistema.*;

/**
 *
 * @author francobmassi
 */
public class CreacionEmplazamientos extends javax.swing.JFrame {
    
    private SoporteTécnico soporteTécnico;
    
    public void setST(SoporteTécnico soporteTécnico){
        this.soporteTécnico = soporteTécnico;
    }
    
    public String strHTML(String texto) {
        return "<html>" + texto + "</html>";
    }
    
    
    /**
     * Creates new form CreacionEmplazamientos
     */
    public CreacionEmplazamientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearProfesores = new javax.swing.JPanel();
        botonVolverAtras2 = new javax.swing.JButton();
        crearEmplazamiento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resultadosDeBusqueda = new javax.swing.JLabel();
        mostrarEmplazamientos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        superficie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        capacidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonVolverAtras2.setText("VOLVER ATRÁS");
        botonVolverAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtras2ActionPerformed(evt);
            }
        });

        crearEmplazamiento.setText("CREAR EMPLAZAMIENTO");
        crearEmplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEmplazamientoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel4.setText("CREAR NUEVO EMPLAZAMIENTO");

        mostrarEmplazamientos.setText("MOSTRAR EMPLAZAMIENTOS EXISTENTES");
        mostrarEmplazamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEmplazamientosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel6.setText("INGRESE EL TIPO DE EMPLAZAMIENTO");

        tipo.setText("Tipo de emplazamiento...");
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel7.setText("INGRESE LA SUPERFICIE DEL EMPLAZAMIENTO");

        superficie.setText("Superficie...");
        superficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superficieActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel8.setText("INGRESE LA CAPACIDAD DEL EMPLAZAMIENTO (CAPACIDAD MÁXIMA = SUPERFICIE/2)");

        capacidad.setText("Capacidad...");
        capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("LISTA DE EMPLAZAMIENTO");

        javax.swing.GroupLayout crearProfesoresLayout = new javax.swing.GroupLayout(crearProfesores);
        crearProfesores.setLayout(crearProfesoresLayout);
        crearProfesoresLayout.setHorizontalGroup(
            crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearProfesoresLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(453, 453, 453))
                    .addGroup(crearProfesoresLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(258, 258, 258))
                    .addGroup(crearProfesoresLayout.createSequentialGroup()
                        .addGroup(crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearEmplazamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(crearProfesoresLayout.createSequentialGroup()
                        .addGroup(crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(crearProfesoresLayout.createSequentialGroup()
                .addGroup(crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(crearProfesoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(mostrarEmplazamientos, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                        .addGroup(crearProfesoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(botonVolverAtras2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(crearProfesoresLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5))
                    .addGroup(crearProfesoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        crearProfesoresLayout.setVerticalGroup(
            crearProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearEmplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarEmplazamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolverAtras2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crearProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crearProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtras2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverAtras2ActionPerformed

    private void crearEmplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEmplazamientoActionPerformed
        String tipo_emp = tipo.getText().toUpperCase();
        String superf = superficie.getText().toUpperCase();
        String capacid = capacidad.getText();
        soporteTécnico.crearEmplazamiento(tipo_emp, superf, capacid);
        tipo.setText("");
        superficie.setText("");
        capacidad.setText("");
    }//GEN-LAST:event_crearEmplazamientoActionPerformed

    private void mostrarEmplazamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEmplazamientosActionPerformed
        String devolver = "";
        for (Emplazamiento emp: soporteTécnico.getEmplazamientos()) {
            devolver += "<p>EMPLAZAMIENTO: " + emp.getTipo() + " - SUPERFICIE: " + emp.getSuperficie() + " - CAPACIDAD: "  + emp.getCapacidad() + ".</p>";
        }
        resultadosDeBusqueda.setText(strHTML(devolver));
    }//GEN-LAST:event_mostrarEmplazamientosActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void superficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superficieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_superficieActionPerformed

    private void capacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolverAtras2;
    private javax.swing.JTextField capacidad;
    private javax.swing.JButton crearEmplazamiento;
    private javax.swing.JPanel crearProfesores;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton mostrarEmplazamientos;
    private javax.swing.JLabel resultadosDeBusqueda;
    private javax.swing.JTextField superficie;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
