/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.Administrador;
import controladores.SoporteTécnico;
import java.time.*;
import java.time.format.*;
import sistema.*;
import articulos.*;

/**
 *
 * @author francobmassi
 */
public class GestionNuevoLoteColchonetas extends javax.swing.JFrame {
    
    private SoporteTécnico soporteTécnico;
    private Administrador admin;
            
    public void setST(SoporteTécnico soporteTécnico){
        this.soporteTécnico = soporteTécnico;
    }
    
    public void setAdmin(Administrador admin){
        this.admin = admin;
    }
    
    private String sedeSeleccionada  = "";
    
    public void setSede(String sede) {
        this.sedeSeleccionada = sede;
    }
    
    /**
     * Creates new form GestionNuevoLoteColchonetas
     */
    public GestionNuevoLoteColchonetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultadosDeBusqueda = new javax.swing.JLabel();
        botonMostrarTiposDeColchonetas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amortizacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ancho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        largo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fechaDeCreacion = new javax.swing.JTextField();
        botonCrearLoteColchoneta = new javax.swing.JButton();
        botonVolverAtras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        botonEliminarLotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMostrarTiposDeColchonetas.setText("MOSTRAR TIPOS DE COLCHONETAS");
        botonMostrarTiposDeColchonetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTiposDeColchonetasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel6.setText("INGRESE LA MARCA DEL PRODUCTO");

        marca.setText("Marca...");
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("NUEVO LOTE DE COLCHONETAS");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel3.setText("INGRESE: \"POR USO\" O \"POR FECHA\".");

        amortizacion.setText("Tipo de amortización...");
        amortizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amortizacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel1.setText("INGRESE EL ANCHO DE LA COLCHONETA");

        ancho.setText("Ancho...");
        ancho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel5.setText("INGRESE EL LARGO");

        largo.setText("Largo");
        largo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel8.setText("INGRESE LA FECHA DE FABRICACION CON EL FORMATO \"AÑO-MES-DIA\" (EJ: \"2023-12-07\")");

        fechaDeCreacion.setText("Fecha de creacion... (NO COMPLETAR ESTE CAMPO SI DESEA ELIMINAR LOTES)");
        fechaDeCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDeCreacionActionPerformed(evt);
            }
        });

        botonCrearLoteColchoneta.setText("CREAR LOTE COLCHONETA");
        botonCrearLoteColchoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearLoteColchonetaActionPerformed(evt);
            }
        });

        botonVolverAtras.setText("VOLVER ATRÁS");
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel7.setText("INGRESE LA CANTIDAD DE ELEMENTOS EN EL LOTE");

        cantidad.setText("Cantidad... (NO COMPLETAR ESTE CAMPO SI DESEA ELIMINAR LOTES)");
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        botonEliminarLotes.setText("ELIMINAR LOTES DE COLCHONETAS");
        botonEliminarLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarLotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearLoteColchoneta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(largo)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amortizacion)
                    .addComponent(marca)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMostrarTiposDeColchonetas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidad)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(473, 473, 473))
                    .addComponent(fechaDeCreacion)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ancho)
                    .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarLotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadosDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonMostrarTiposDeColchonetas)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amortizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(largo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaDeCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearLoteColchoneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarLotes)
                .addGap(18, 18, 18)
                .addComponent(botonVolverAtras)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarTiposDeColchonetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTiposDeColchonetasActionPerformed
        String devolver = "";
        for (Articulo art: soporteTécnico.getArticulos()){
            if (art instanceof Colchoneta) {
                Colchoneta colch = (Colchoneta) art;
                devolver += "<p>ARTICULO: " + colch.getTipo() + " - " + colch.getMarca()
                + " - " + colch.getTipoAmortizacion() + " - " + colch.getDuracion()
                + " -  DIMENSIONES:  " + colch.getLargo() + "mts de largo X " + colch.getAncho() + "mts de ancho.</p>";
            }
        }
        resultadosDeBusqueda.setText(strHTML(devolver));
    }//GEN-LAST:event_botonMostrarTiposDeColchonetasActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    private void amortizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amortizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amortizacionActionPerformed

    private void anchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoActionPerformed

    private void largoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoActionPerformed

    private void fechaDeCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDeCreacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDeCreacionActionPerformed

    private void botonCrearLoteColchonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearLoteColchonetaActionPerformed
        String fabricante = marca.getText();
        String tipo_amortizacion = amortizacion.getText().toUpperCase();
        String fecha = fechaDeCreacion.getText();
        String anchoSTR = ancho.getText().toUpperCase();
        String largoSTR = largo.getText();
        String cantidadSTR = cantidad.getText();
        try {
            if (!tipo_amortizacion.equals("POR USO") && !tipo_amortizacion.equals("POR FECHA")) {
                IngresoErroneo ingresoErroneo = new IngresoErroneo();
                ingresoErroneo.setVisible(true);
                ingresoErroneo.setLocationRelativeTo(null);
            } else {
                //admin.agregarArticulos("Recoleta", "PESA", "Gadnic", "Por uso", "2023-12-06", "50", "3", "De tobillera", null, null, null);
                admin.agregarArticulos(sedeSeleccionada, "COLCHONETA", fabricante, tipo_amortizacion, fecha, cantidadSTR, null, null, largoSTR, anchoSTR, null);
            }
        } catch (DateTimeParseException e) {
            IngresoErroneo ingresoErroneo = new IngresoErroneo();
            ingresoErroneo.setVisible(true);
            ingresoErroneo.setLocationRelativeTo(null);
        }
        marca.setText("");
        amortizacion.setText("");
        ancho.setText("");
        largo.setText("");
        cantidad.setText("");
        fechaDeCreacion.setText("");
    }//GEN-LAST:event_botonCrearLoteColchonetaActionPerformed

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverAtrasActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void botonEliminarLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarLotesActionPerformed
        String fabricante = marca.getText();
        String tipo_amortizacion = amortizacion.getText().toUpperCase();
        String anchoSTR = ancho.getText().toUpperCase();
        String largoSTR = largo.getText();
        try {
            if (!tipo_amortizacion.equals("POR USO") && !tipo_amortizacion.equals("POR FECHA")) {
                IngresoErroneo ingresoErroneo = new IngresoErroneo();
                ingresoErroneo.setVisible(true);
                ingresoErroneo.setLocationRelativeTo(null);
            } else {
                //admin.agregarArticulos("Recoleta", "PESA", "Gadnic", "Por uso", "2023-12-06", "50", "3", "De tobillera", null, null, null);
                admin.eliminarArticuloDeSede(sedeSeleccionada, "COLCHONETA", fabricante, tipo_amortizacion, null, null, largoSTR, anchoSTR, null);
            }
        } catch (DateTimeParseException e) {
            IngresoErroneo ingresoErroneo = new IngresoErroneo();
            ingresoErroneo.setVisible(true);
            ingresoErroneo.setLocationRelativeTo(null);
        }
        marca.setText("");
        amortizacion.setText("");
        ancho.setText("");
        largo.setText("");
        cantidad.setText("");
        fechaDeCreacion.setText("");
    }//GEN-LAST:event_botonEliminarLotesActionPerformed


    public String strHTML(String texto) {
        return "<html>" + texto + "</html>";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amortizacion;
    private javax.swing.JTextField ancho;
    private javax.swing.JButton botonCrearLoteColchoneta;
    private javax.swing.JButton botonEliminarLotes;
    private javax.swing.JButton botonMostrarTiposDeColchonetas;
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField fechaDeCreacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField largo;
    private javax.swing.JTextField marca;
    private javax.swing.JLabel resultadosDeBusqueda;
    // End of variables declaration//GEN-END:variables
}
