/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.SoporteTécnico;

/**
 *
 * @author francobmassi
 */
public class PanelDeControlST extends javax.swing.JFrame {
    
    private SoporteTécnico soporteTécnico;
    
    public void setST(SoporteTécnico soporteTécnico){
        this.soporteTécnico = soporteTécnico;
    }
    /**
     * Creates new form PanelDeControlST
     */
    public PanelDeControlST() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCrearSede = new javax.swing.JButton();
        botonGestionarClientes = new javax.swing.JButton();
        botonGestionarAdministrador = new javax.swing.JButton();
        botonCrearClases = new javax.swing.JButton();
        botonAsignarSedes = new javax.swing.JButton();
        botonCrearArticulos = new javax.swing.JButton();
        botonVolverAtras = new javax.swing.JButton();
        botonCrearDisciplina = new javax.swing.JButton();
        botonCrearProfesores = new javax.swing.JButton();
        botonVerSedes = new javax.swing.JButton();
        botonCrearEmplazamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonCrearSede.setText("CREAR SEDES");
        botonCrearSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearSedeActionPerformed(evt);
            }
        });

        botonGestionarClientes.setText("GESTIONAR USUARIOS CLIENTES");
        botonGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarClientesActionPerformed(evt);
            }
        });

        botonGestionarAdministrador.setText("GESTIONAR USUARIOS ADMINISTRADORES");
        botonGestionarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarAdministradorActionPerformed(evt);
            }
        });

        botonCrearClases.setText("CREAR CLASES");
        botonCrearClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearClasesActionPerformed(evt);
            }
        });

        botonAsignarSedes.setText("ASIGNAR SEDES");
        botonAsignarSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarSedesActionPerformed(evt);
            }
        });

        botonCrearArticulos.setText("CREAR ARTICULOS");
        botonCrearArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearArticulosActionPerformed(evt);
            }
        });

        botonVolverAtras.setText("VOLVER ATRÁS");
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });

        botonCrearDisciplina.setText("CREAR DISCIPLINA");
        botonCrearDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearDisciplinaActionPerformed(evt);
            }
        });

        botonCrearProfesores.setText("CREAR PROFESORES");
        botonCrearProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearProfesoresActionPerformed(evt);
            }
        });

        botonVerSedes.setText("VER SEDES DE LA CADENA");
        botonVerSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerSedesActionPerformed(evt);
            }
        });

        botonCrearEmplazamiento.setText("CREAR EMPLAZAMIENTO");
        botonCrearEmplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearEmplazamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrearClases, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonGestionarAdministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonGestionarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonAsignarSedes, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonCrearArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonCrearDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonCrearProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(botonVerSedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrearEmplazamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCrearSede, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGestionarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAsignarSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearEmplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearClases, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(botonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearSedeActionPerformed
        CreacionDeSedes crearSedes = new CreacionDeSedes();
        crearSedes.setST(soporteTécnico);
        crearSedes.setVisible(true);
        crearSedes.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCrearSedeActionPerformed

    private void botonGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarClientesActionPerformed
        GestionDeClientes gestionDeClientes = new GestionDeClientes();
        gestionDeClientes.setST(soporteTécnico);
        gestionDeClientes.setVisible(true);
        gestionDeClientes.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonGestionarClientesActionPerformed

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverAtrasActionPerformed

    private void botonCrearDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearDisciplinaActionPerformed
        CreacionDisciplina crearDisciplina = new CreacionDisciplina();
        crearDisciplina.setST(soporteTécnico);
        crearDisciplina.setVisible(true);
        crearDisciplina.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCrearDisciplinaActionPerformed

    private void botonCrearProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearProfesoresActionPerformed
        CreacionProfesores creacionProfesor = new CreacionProfesores();
        creacionProfesor.setST(soporteTécnico);
        creacionProfesor.setVisible(true);
        creacionProfesor.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCrearProfesoresActionPerformed

    private void botonVerSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerSedesActionPerformed
        VerSedes verSedes = new VerSedes();
        verSedes.setST(soporteTécnico);
        verSedes.setVisible(true);
        verSedes.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonVerSedesActionPerformed

    private void botonGestionarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarAdministradorActionPerformed
        GestionDeAdministradores gestionDeAdministradores = new GestionDeAdministradores();
        gestionDeAdministradores.setST(soporteTécnico);
        gestionDeAdministradores.setVisible(true);
        gestionDeAdministradores.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonGestionarAdministradorActionPerformed

    private void botonAsignarSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarSedesActionPerformed
        AsignarSedes asignarSedes = new AsignarSedes();
        asignarSedes.setST(soporteTécnico);
        asignarSedes.setVisible(true);
        asignarSedes.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonAsignarSedesActionPerformed

    private void botonCrearEmplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearEmplazamientoActionPerformed
        CreacionEmplazamientos crearEmplazamientos = new CreacionEmplazamientos();
        crearEmplazamientos.setST(soporteTécnico);
        crearEmplazamientos.setVisible(true);
        crearEmplazamientos.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCrearEmplazamientoActionPerformed

    private void botonCrearArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearArticulosActionPerformed
        CreacionDeArticulos crearArticulos = new CreacionDeArticulos();
        crearArticulos.setST(soporteTécnico);
        crearArticulos.setVisible(true);
        crearArticulos.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCrearArticulosActionPerformed

    private void botonCrearClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearClasesActionPerformed
        CreacionClases crearClases = new CreacionClases();
        crearClases.setST(soporteTécnico);
        crearClases.setVisible(true);
        crearClases.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonCrearClasesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignarSedes;
    private javax.swing.JButton botonCrearArticulos;
    private javax.swing.JButton botonCrearClases;
    private javax.swing.JButton botonCrearDisciplina;
    private javax.swing.JButton botonCrearEmplazamiento;
    private javax.swing.JButton botonCrearProfesores;
    private javax.swing.JButton botonCrearSede;
    private javax.swing.JButton botonGestionarAdministrador;
    private javax.swing.JButton botonGestionarClientes;
    private javax.swing.JButton botonVerSedes;
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
